name: Build and publish

on:
  push:
    paths:
      - "patches/api/*.patch"
      - "patches/server/*.patch"
    branches:
      - "master"
  workflow_dispatch:

permissions:
  packages: read
  actions: read
  contents: read

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: NetherRealmSpigot/reusable-actions/Panda@main
        with:
          build-ref: ${{ github.ref }}
          maven: ${{ secrets.PANDASPIGOT_MAVEN }}
          maven-username: ${{ secrets.PANDASPIGOT_MAVEN_USERNAME }}
          maven-password: ${{ secrets.PANDASPIGOT_MAVEN_PASSWORD }}
